name: rest_api_client
description: REST API Clients.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dio: ^5.1.1
  retrofit: ^4.0.1
  riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2

dev_dependencies:
  altive_lints: ^1.6.1
  build_runner: ^2.2.0
  retrofit_generator: ^6.0.0+1
  riverpod_generator: ^2.1.4
  test: ^1.21.1
